//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ModelCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarTenant
    {
        public int CarID { get; set; }
        public int TenantID { get; set; }
        public System.DateTime StartDatetime { get; set; }
        public Nullable<System.DateTime> EndDatetime { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
