//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ModelCar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZhangDasiDBEntities : DbContext
    {
        public ZhangDasiDBEntities()
            : base("name=ZhangDasiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tenant> Tenant { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<CarContact> CarContact { get; set; }
        public virtual DbSet<CarManual> CarManual { get; set; }
        public virtual DbSet<CarTenant> CarTenant { get; set; }
        public virtual DbSet<TestTT> TestTT { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
    }
}
